### ISSUE TITLE
install i5ting_toc failed

### ISSUE THREAD

**Issue by l1t1** [i5ting/tocmd.npm#12]
I use the node binary https://registry.npmmirror.com/-/binary/node/v13.14.0/node-v13.14.0-win-x64.7z on windows 7
```
D:\node>npm install -g i5ting_toc
npm ERR! code ETIMEOUT
npm ERR! errno ETIMEOUT
npm ERR! request to https://registry.npmjs.org/i5ting_toc/-/i5ting_toc-1.1.5.tgz failed, reason: A "socket" was not created for HTTP request before 30001ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LD\AppData\Roaming\npm-cache\_logs\2024-09-12T00_29_09_317Z-debug.log

D:\node>node -v
v13.14.0
```

**Comment by l1t1** [comment]
the log file
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\node\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'i5ting_toc'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose npm-session 75acdbf141fa6006
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/i5ting_toc 1058ms
8 silly fetchPackageMetaData error for i5ting_toc@latest request to https://registry.npmjs.org/i5ting_toc/-/i5ting_toc-1.1.5.tgz failed, reason: A "socket" was not created for HTTP request before 30001ms
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 31111ms
11 verbose type system
12 verbose stack FetchError: request to https://registry.npmjs.org/i5ting_toc/-/i5ting_toc-1.1.5.tgz failed, reason: A "socket" was not created for HTTP request before 30001ms
12 verbose stack     at ClientRequest.<anonymous> (D:\node\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:315:20)
12 verbose stack     at onerror (D:\node\node_modules\npm\node_modules\agent-base\index.js:101:9)
12 verbose stack     at Timeout.ontimeout [as _onTimeout] (D:\node\node_modules\npm\node_modules\agent-base\index.js:114:5)
12 verbose stack     at listOnTimeout (internal/timers.js:549:17)
12 verbose stack     at processTimers (internal/timers.js:492:7)
13 verbose cwd D:\node
14 verbose Windows_NT 6.1.7601
15 verbose argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "i5ting_toc"
16 verbose node v13.14.0
17 verbose npm  v6.14.4
18 error code ETIMEOUT
19 error errno ETIMEOUT
20 error request to https://registry.npmjs.org/i5ting_toc/-/i5ting_toc-1.1.5.tgz failed, reason: A "socket" was not created for HTTP request before 30001ms
21 verbose exit [ 1, true ]
```
